{{- if .Values.graphiti.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "quorum.graphiti.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "quorum.graphiti.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.graphiti.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "quorum.graphiti.selectorLabels" . | nindent 4 }}
{{- end -}}
