{{- if .Values.gateway.enabled -}}
{{- if not .Values.gateway.jwtSecret.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quorum.gateway.fullname" . }}-jwt-keys
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "quorum.gateway.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.gateway.jwtSecret.privateKey }}
  QUORUM_JWT_PRIVATE_KEY: {{ .Values.gateway.jwtSecret.privateKey | b64enc | quote }}
  {{- else }}
  QUORUM_JWT_PRIVATE_KEY: ""
  {{- end }}
  {{- if .Values.gateway.jwtSecret.publicKey }}
  QUORUM_JWT_PUBLIC_KEY: {{ .Values.gateway.jwtSecret.publicKey | b64enc | quote }}
  {{- else }}
  QUORUM_JWT_PUBLIC_KEY: ""
  {{- end }}
{{- end -}}
{{- end -}}
